#!/usr/bin/perl

use strict;
use utf8;
use Text::ParseWords;
use Getopt::Long;

################################################################
# Difinition list; this is the 1st line of file.
################################################################
my @ad_dsattr = (
    "DN",
    "objectClass",
    "distinguishedName",
    "instanceType",
    "name",
    "objectCategory",
    "cn",
    "displayName",
    "sAMAccountName",
    "sn",
    "givenName",
    "userPrincipalName",
    "homeDirectory",
    "homeDrive",
);
my $addomain;
my @domainlabels;
my $homedrivelabel;
my $help;
my @items;
my @dsattr;
my $thisScript;
my $quote_sw;
my %dsAttr;
my $myouji;
my $oname;
my $debug;
my $i;
my $DC_SUFFIX;

GetOptions (
        "addomain:s"		=> \$addomain,
        "homedrivelabel:s"	=> \$homedrivelabel,
        "help!"			=> \$help,
    "debug!"		=> \$debug,
);

# Show help
if ($help){
        &usage();
        exit;
}

# PRINT 1st definition line.
print ( join (',', @ad_dsattr), "\n");

# Parsing and out put.
while(<>){
    # Parsing
    chomp;
    s/,$//;

    next if /^\s*$/;
    next if /^\s*\#/;
    next if /^,,,/;
    @items = &trim ( quotewords( "," ,$quote_sw, $_ ) ) ;

    $dsAttr{"RealName"}	= $items[0];
    $dsAttr{"cn"}		= $dsAttr{"RealName"};
    $dsAttr{"displayName"}	= $dsAttr{"RealName"};
    $dsAttr{"name"}		= $dsAttr{"RealName"};
    ($myouji, $oname)	= split(/ /,$dsAttr{"RealName"});
    $dsAttr{"LastName"}     = "$myouji";
    $dsAttr{"FirstName"}    = "$oname";
    $dsAttr{"RecordName"}	= lc $items[1];
    $dsAttr{"sAMAccountName"} = $dsAttr{"RecordName"};
    $dsAttr{"HomeServer"}	= lc $items[6];
    $homedrivelabel	= uc $homedrivelabel ;
    $homedrivelabel = $homedrivelabel . ":" unless ( $homedrivelabel =~ /:$/ );
    $dsAttr{"homeDrive"}	= $homedrivelabel;
    $dsAttr{"homeDirectory"} = "\\\\\\\\" . $dsAttr{"HomeServer"} .
    "\\\\" . $items[7] . "\\\\". $dsAttr{"RecordName"} ;
    $dsAttr{"userPrincipalName"} = $dsAttr{"RecordName"}  . "@" . $addomain;
    $dsAttr{"sn"}		= $dsAttr{"LastName"};
    $dsAttr{"givenName"}	= $dsAttr{"FirstName"};

    $dsAttr{"objectClass"}	= "user";
    $dsAttr{"instanceType"}	= 4;

    $DC_SUFFIX = $addomain;
    $DC_SUFFIX =~ s/\./,DC=/g;
    $DC_SUFFIX = "DC=" .  $DC_SUFFIX;


    $dsAttr{"DN"} = "\"" . "CN=" . $dsAttr{"cn"} . ",CN=Users," . $DC_SUFFIX . "\"";
    $dsAttr{"distinguishedName"} = $dsAttr{"DN"};
    $dsAttr{"objectCategory"} =  "\"" . "CN=Person,CN=Schema,CN=Configuration," . $DC_SUFFIX . "\"";

    if ( $debug ){
    print "#______S_T_A_R_T_______D_E_B_U_G__________________________\n";
    print "# AD Domain is $addomain\n";
    print "# Home drive label is $homedrivelabel\n";
    print "\n";
    print "# Realname is $dsAttr{RealName}\n";
    print "# Last Name is $dsAttr{LastName}\n";
    print "# First Name is $dsAttr{FirstName}\n";
    print "# Record Name is $dsAttr{RecordName}\n";
    print "# Home Server is $dsAttr{HomeServer}\n";

    print "\n";
    for ( $i = 0; $i <= $#ad_dsattr ; $i++ ){
    print "[$i]:$ad_dsattr[$i] is $dsAttr{$ad_dsattr[$i]}\n";
    }
    print "#______E_N_D____o_f____D_E_B_U_G__________________________\n";

    }

    for ( $i = 0; $i < $#ad_dsattr ; $i++ ){
    print "$dsAttr{$ad_dsattr[$i]},";
    }
    print "$dsAttr{$ad_dsattr[$#ad_dsattr]}\r\n";
}

########################################################
# SUB FUNCTIONS
#########################################################
sub trim (){
        my @out = @_;
        for (@out) { s/^\s+// ; s/\s+$// ; }
        return wantarray ? @out : $out[0];
}

sub usage(){
        my $myf = `/usr/bin/basename $0`;
        chomp $myf;
        print <<__USE__

#####################################
              U S A G E
#####################################

Hi $ENV{USER}.

examples)
   $myf --addomain ad.domain.net --homedrivelabel H /path/to/csvfile
   $myf --help
   $myf --debug

__USE__
}
