#!/usr/bin/perl

use strict;
use Getopt::Long;


my (  $silent, $help, @userinfo, $mod, $msg);
GetOptions(
    "help!"       => \$help,
    "silent!"  => \$silent,
    "mod!"     => \$mod,
    );

if ($help){
    print <<_HOWTO_

########################################
              U S A G E
########################################

Hi $ENV{USER}.

$0 has three options.
        --help      ; show this message.
        --silent    ; do not process message.
        --mod       ; do not process message.

$0 expects a unix /etc/passwd file format.
But it MUST have plain password string when you're going
to add user accounts.

$0 requires the root privilege! please use `sudo(8)' command.

_HOWTO_
;
    exit 0;
}

if ( $< != 0) { die "Need root privilege! Use `sudo(8)'.\n"; };
while(<>){
    @userinfo = split(/:/);
    if ( $userinfo[0] =~ /\$/ ){
            $userinfo[0] =~ s/\$//;
            open(CMD, "| /usr/bin/smbpasswd -m -as $userinfo[0] > /dev/null");
            close(CMD);
    print ( "Added machine account: $userinfo[0]\n") unless ( $silent);
    }else{
    if ( $mod ){
                open(CMD, "| /usr/bin/smbpasswd -s $userinfo[0] > /dev/null");
    $msg = "Modified";
    }else{
                open(CMD, "| /usr/bin/smbpasswd -as $userinfo[0] > /dev/null");
    $msg = "Added";
    }
            print CMD "$userinfo[1]\n$userinfo[1]\n";
            close(CMD);
    print ( "$msg user account: $userinfo[0]\n") unless ( $silent);
    }
}
